apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: namespaced-db-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: namespaced-db-operator-system
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: namespaced-db-operator-system
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: sampledb-secret
  namespace: namespaced-db-operator-system
type: Opaque
data:
  username: c2FtcGxldXNlcg==
  password: c2FtcGxlcGFzc3dvcmQ=