## Append samples you want in your CSV to this file as resources ##
resources:
- db_v1alpha1_databaseinstance.yaml
- db.yaml
- db_v1alpha1_database.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
